'use strict';
var TG = {};
TG.Engines = {};
TG.Content = {};
TG.Objects = {};
TG.Objects.Animation = {};

document.write('<script src="JS/Content/constants.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Animation/Frame.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Animation/Render.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Animation/Sequence.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Position.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Projectile.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Item.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/NPC.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Plant.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Water.js" type="text/javascript"></script>');
document.write('<script src="JS/Objects/Sex.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/save.js" type="text/javascript"></script>');
document.write('<script src="JS/Test/test.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/input.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/movement.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/renderCanvas.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/AI.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/debug.js" type="text/javascript"></script>');
document.write('<script src="JS/Content/constants.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/core.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/Consumables.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/Weapons.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/Plants.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/Player.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/NPC.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/Water.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Generate/Sex.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Relationships.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/Chrono.js" type="text/javascript"></script>');
document.write('<script src="JS/Engines/GameCore.js" type="text/javascript"></script>');
document.write('<script src="JS/Content/comm.js" type="text/javascript"></script>');